sudo: required
language: generic 
services:
 - docker

before_install:
 - docker build -t mohanrajanna/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true mohanrajanna/docker-react npm run test